### ISSUE TITLE
Add deprecated test in TMAP8 Civet

### ISSUE THREAD

**Issue by simopier** [idaholab/TMAP8#136]
## Reason
Adding deprecated tests in TMAP8 Civet would help us catch deprecated code during PRs.

## Design
Add new recipe for deprecated test - it could be an optional one.

## Impact
Improve testing.

**Comment by simopier** [comment]
@loganharbour, I think this is your domain, but let me know if I need to reach out to someone else. 
@cticenhour  FYI.

**Comment by loganharbour** [comment]
The recipe is complete and merged.
