### ISSUE TITLE
TMAP8 needs getting started instructions

### ISSUE THREAD

**Issue by cticenhour** [idaholab/TMAP8#19]
TMAP8 does not have getting started instructions for users who are handed the URL to the code documentation site. This should be written and a clean-up of the homepage should be performed so that users can get started more easily.

**Comment by ke7kto** [comment]
Shouldn't the README also have the url to the TMAP8 code documentation site? I thought about making a new issue and submitting it, but want to make sure it's not a design choice.

**Comment by cticenhour** [comment]
The contents of the readme as they are currently were what the standard was for the technology deployment department when we got the clear to open source. Those elements should remain, but we can add the URL to it, no problem.
