### ISSUE TITLE
Some issues in verification case ver-1g

### ISSUE THREAD

**Issue by ChaitanyaBhave-e** [idaholab/TMAP8#84]
## Bug Description
There's a few minor issues with this verification case:
1. Wrong csv file name for the same concentration case in the Python script on [line 30](https://github.com/idaholab/TMAP8/blob/c711bc80a10bddee5319d0d560a10a63dd5346e3/test/tests/ver-1g/comparison_ver-1g.py#L68).
2. The different concentration MOOSE [input file](https://github.com/idaholab/TMAP8/blob/c711bc80a10bddee5319d0d560a10a63dd5346e3/test/tests/ver-1g/ver-1g_diff_conc.i#L11) uses the wrong initial value of c_b, which is why the numerical solution never reaches the analytical prediction. Initial value from analytical model is 1.215e-4, input file uses 1.225e-4
3. The error added to concB_o in the Python script for the [different concentration](https://github.com/idaholab/TMAP8/blob/c711bc80a10bddee5319d0d560a10a63dd5346e3/test/tests/ver-1g/comparison_ver-1g.py#L17) case is unnecessary. The same error in the [equal concentration](https://github.com/idaholab/TMAP8/blob/c711bc80a10bddee5319d0d560a10a63dd5346e3/test/tests/ver-1g/comparison_ver-1g.py#L55) case prevents a divide by zero error. Worth checking if the analytical solution applies if the correct values create a divide by zero error.

## Impact
Fixing these bugs makes the verification test script work properly, and removes the apparent error between the numerical solution and analytical model.

**Comment by ChaitanyaBhave-e** [comment]
@simopier @cticenhour

**Comment by RemDelaporteMathurin** [comment]
Good catch @ChaitanyaBhave-e ! How come these weren't caught by the CI?

**Comment by ChaitanyaBhave-e** [comment]
@RemDelaporteMathurin I think it's because the Python scripts aren't currently set up to run as tests. They're set up to be manually run by the users. Rendering the figures in real time for the documentation and having a test that checks for the RMSE of the analytical solution vs MOOSE solution should fix this issue in the future.

**Comment by ChaitanyaBhave-e** [comment]
Regarding point three in my issue, I realized that the correct analytical solution for equal concentration is already provided in the documentation for this verification. The Python script uses the wrong analytical solution, which is why it needed to add that error term. We should fix this and add the right expression.
