### ISSUE TITLE
Adding coverage information for new PRs

### ISSUE THREAD

**Issue by simopier** [idaholab/TMAP8#93]
## Reason
I currently do not think that we test coverage in PRs. We might want to add this sooner rather than later to ensure good coverage.

## Design
Add coverage testing during PRs like in other applications. 

## Impact
It becomes easier to ensure high test coverage.

**Comment by simopier** [comment]
@cticenhour @loganharbour, I think that would be great to add this.

**Comment by cticenhour** [comment]
Closing with the merge of #100. Coverage is now being generated for all pull requests.
